version: '3'
services:
    frontend:
        build: .
        container_name: frontend
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            - ./:/frontend
            #- /nginx/certs:/etc/nginx/certs
            - /frontend/node_modules

